---
# tasks file for RHEL7-CIS
- include: prelim.yml
  become: yes
  tags:
      - prelim_tasks
      - always

- include: section1.yml
  become: yes
  when: rhel7cis_section1|bool
  tags:
      - rhel7cis_section1

- include: section2.yml
  become: yes
  when: rhel7cis_section2|bool

- include: section3.yml
  become: yes
  when: rhel7cis_section3|bool

- include: section4.yml
  become: yes
  when: rhel7cis_section4|bool

- include: section5.yml
  become: yes
  when: rhel7cis_section5|bool

- include: section6.yml
  become: yes
  when: rhel7cis_section6|bool

- include: post.yml
  become: yes
  tags:
      - post_tasks
      - always
