---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: passwd
  changed_when: no
  check_mode: no

- name: "PRELIM | List home directories"
  find:
      paths:
          - /home
      patterns:
          - '.bash_profile'
      depth: 2
      recurse: yes
      hidden: yes
  register: homes

- name: "PRELIM | Resolve home directories to usernames"
  command: "id -un {{ item }}"
  with_items: "{{ homes | json_query('files[*].path') | map('dirname') | map('basename') | list }}"
  changed_when: no
  check_mode: no
  ignore_errors: yes
  register: home_usernames

- name: "PRELIM | List all users"
  set_fact:
      users: "{{ list_passwd | union(list_homes) | unique }}"
  vars:
      list_passwd: "{{ passwd | json_query('stdout_lines') }}"
      list_homes: "{{ home_usernames.results | json_query('[*].stdout') }}"

- name: "PRELIM | Gather accounts with empty password fields"
  command: "awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}' /etc/shadow"
  register: empty_password_accounts
  changed_when: no
  check_mode: no

- name: "PRELIM | Gather UID 0 accounts other than root"
  command: "awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}' /etc/passwd"
  register: uid_zero_accounts_except_root
  changed_when: no
  check_mode: no

- name: "PRELIM | Section 4.1 | Configure System Accounting (auditd)"
  yum:
      name: audit
      state: present

- name: "PRELIM | Section 5.1 | Check cron"
  yum:
      name: cronie
      state: present

- name: "PRELIM | Check if prelink package is installed"
  command: rpm -q prelink
  args:
      warn: false
  register: prelink_installed
  changed_when: no
  failed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint


# Individual service checks
- name: "PRELIM | Check for xinetd service"
  shell: "systemctl show xinetd | grep LoadState | cut -d = -f 2"
  register: xinetd_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint #  ANSIBLE0006


- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: autofs_service_status
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_lint #  ANSIBLE0006

- name: "PRELIM | Check for tmp.mount"
  stat:
      path: /etc/systemd/system/tmp.mount
  register: tmp_mount
  changed_when: no
  check_mode: no
  tags:
      - skip_ansible_tmp_mount

