- name: " 4.2.3 || Ensure rsyslog"
  yum:
      name: "{{ rhel7cis_syslog }}"
      state: present
  when:
      - rhel7cis_rule_4_2_3|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.3

- name: " 4.2.1.1 || Ensure rsyslog Service is enabled"
  service:
      name: rsyslog
      state: started
      enabled: yes
  changed_when: no
  when:
      - rhel7cis_rule_4_2_1_1|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.1
      - notimplemented

- name: "4.2.1.2 || Ensure logging is configured"
  blockinfile:
    path: /etc/rsyslog.conf
    backup: yes
    block: |
      *.emerg                 :omusrmsg:*
      mail.*                  -/var/log/mail
      mail.info               -/var/log/mail.info
      mail.warning            -/var/log/mail.warn
      mail.err                 /var/log/mail.err
      news.crit               -/var/log/news/news.crit
      news.err                -/var/log/news/news.err
      news.notice             -/var/log/news/news.notice
      *.=warning;*.=err       -/var/log/warn
      *.crit                   /var/log/warn
      *.*;mail.none;news.none -/var/log/messages
      local0,local1.*         -/var/log/localmessages
      local2,local3.*         -/var/log/localmessages
      local4,local5.*         -/var/log/localmessages
      local6,local7.*         -/var/log/localmessages
  changed_when: no
  when:
      - rhel7cis_rule_4_2_1_2|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.2
      - notimplemented

- name: " 4.2.1.3 || Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  when:
      - rhel7cis_rule_4_2_1_3|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.3
      
## where loghost.example.com is the name of your central log host  zjistit co e nas central log host ci to mame
- name: " 4.2.1.4 || Ensure rsyslog is configured to send logs to a remote log host"
  lineinfile:
    path: /etc/rsyslog.conf
    backup: yes
    block: |
      action(type="omfwd" target="{{ remoteSyslog.host }}" port="{{ remoteSyslog.port }}" protocol="{{ remoteSyslog.protocol }}" action.resumeRetryCount="100" queue.type="LinkedList" queue.size="1000")
  when:
      - rhel7cis_rule_4_2_1_4|bool
  tags:
      - level1
      - rule_4.2.1.4

- name: "4.2.1.5 || Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$ModLoad'
    line: "$ModLoad imtcp"
  with_items:
  - { name: restart.rsyslog }
  when:
      - rhel7cis_rule_4_2_1_5|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.5

- name: "4.2.1.5 || Ensure remote rsyslog messages are only accepted on designated log hosts."
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$InputTCPServerRun'
    line: "$InputTCPServerRun 514"
  with_items:
    - { name: restart.rsyslog }
  when:
      - rhel7cis_rule_4_2_1_5|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.1.5



- name: "4.2.2.1 | Ensure journald is configured to send logs to rsyslog"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?ForwardToSyslog=(yes|no)"
    line: ForwardToSyslog=yes
  when:
      - rhel7cis_rule_4_2_2_1|bool
  tags:
      - level1
      - rule_4.2.2.1

- name: "4.2.2.2.2 Ensure journald is configured to compress large log files"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Compress=(yes|no)"
    line: Compress=yes
  when:
      - rhel7cis_rule_4_2_2_2_2|bool
  tags:
      - level1
      - rule_4.2.2.2.2

- name: "4.2.2.3 Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Storage=(auto|persistent)"
    line: Storage=persistent
  with_items:
    - { name: restart.journald }
  when:
      - rhel7cis_rule_4_2_2_3|bool
  tags:
      - level1
      - rule_4.2.2.3


- name: "4.2.2.2 || Ensure logging is configured"
  blockinfile:
    path: /etc/rsyslog.conf
    backup: yes
    block: |
      *.emerg                 :omusrmsg:*
      mail.*                  -/var/log/mail
      mail.info               -/var/log/mail.info
      mail.warning            -/var/log/mail.warn
      mail.err                 /var/log/mail.err
      news.crit               -/var/log/news/news.crit
      news.err                -/var/log/news/news.err
      news.notice             -/var/log/news/news.notice
      *.=warning;*.=err       -/var/log/warn
      *.crit                   /var/log/warn
      *.*;mail.none;news.none -/var/log/messages
      local0,local1.*         -/var/log/localmessages
      local2,local3.*         -/var/log/localmessages
      local4,local5.*         -/var/log/localmessages
      local6,local7.*         -/var/log/localmessages
  changed_when: no
  when:
      - rhel7cis_rule_4_2_2_2|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.2.2
      - notimplemented


- name: " 4.2.4 || Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  changed_when: no
  failed_when: no
  when:
      - rhel7cis_rule_4_2_4|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.2.4

- name: "4.3 || Ensure logrotate is configured"
  find:
      paths: /etc/logrotate.d/
  register: log_rotates
  tags:
      - level1
      - level2
      - patch
      - rule_4.3

- name: "4.3 || Ensure logrotate is configured"
  replace:
      path: "{{ item.path }}"
      regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
      replace: "\\1{{ rhel7cis_logrotate }}"
  with_items:
      - "{{ log_rotates.files }}"
      - { path: "/etc/logrotate.conf" }
  when:
      - rhel7cis_rule_4_3|bool
  tags:
      - level1
      - level2
      - patch
      - rule_4.3
