- name: "| 2.1.7 | Ensure xinetd is not installed"
  yum:
      name: xinetd
      state: absent
  when:
      - rhel7cis_rule_2_1_7|bool
  tags:
      - level1
      - patch
      - scored
      - rule_2.1.7

- name: " 2.2.1.1 | Ensure time synchronization is in use - service install"
  yum:
      name: "{{ rhel7cis_time_synchronization }}"
      state: present
  when:
      - rhel7cis_rule_2_2_1_1|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: " 2.2.1.1 | Ensure time synchronization is in use - service start"
  service:
      name: "{{ rhel7cis_time_synchronization }}d"
      state: started
      enabled: yes
  when:
      - rhel7cis_rule_2_2_1_1|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "| 2.2.1.2 | Ensure ntp is configured | modify /etc/sysconfig/ntpd"   
  #### Notimplemented default na CentOS Azure image je chronyd
  debug:
    msg: "-->  Notimplemented default na CentOS Azure image je chronyd"
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "| 2.2.1.3 | Ensure chrony is configured"
  template:
      src: chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_time_synchronization == "chrony"
      - rhel7cis_rule_2_2_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "| 2.2.1.3 | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
  lineinfile:
      dest: /etc/sysconfig/chronyd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u chrony\""
      state: present
      create: yes
  when:
      - rhel7cis_time_synchronization == "chrony"
      - rhel7cis_rule_2_2_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "| 2.2.2 | Ensure X11 Server components are not installed"
  yum:
      state: absent
      name:
          - "@X Window System"
          - "xorg-x11*"
  when:
      - not rhel7cis_xwindows_required
      - rhel7cis_rule_2_2_2|bool
  tags:
      - level1
      - scored
      - xwindows
      - patch
      - rule_2.2.2

- name: "| 2.2.3 | Ensure Avahi Server is not installed"
  yum:
      name: avahi-daemon
      state: absent
  when:
      - not rhel7cis_avahi_server
      - rhel7cis_rule_2_2_3|bool
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.2.3

- name: "| 2.2.4 | Ensure CUPS is not installed"
  yum:
      name: cups
      state: absent
  when:
      - not rhel7cis_cups_server
      - rhel7cis_rule_2_2_4|bool
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.2.4

- name: "| 2.2.5 | Ensure DHCP Server is not installed"
  yum:
      name: dhcpd
      state: absent
  when:
      - not rhel7cis_dhcp_server
      - rhel7cis_rule_2_2_5|bool
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.2.5

- name: "| 2.2.6 | Ensure LDAP server is not installed"
  yum:
      name: slapd
      state: absent
  when:
      - not rhel7cis_ldap_server
      - rhel7cis_rule_2_2_6|bool
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.2.6

- name: "| 2.2.7 | Ensure nfs-utils is not installed"
  yum:
      name: nfs-utils
      state: absent
  when:
      - not rhel7cis_nfs_rpc_server
      - rhel7cis_rule_2_2_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "| 2.2.7 | Ensure rpcbind is not installed"
  yum:
      name: rpcbind
      state: absent
  when:
      - not rhel7cis_nfs_rpc_server
      - rhel7cis_rule_2_2_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "| 2.2.8 | Ensure DNS Server is not installed"
  yum:
      name: named
      state: absent
  when:
      - not rhel7cis_named_server
      - rhel7cis_rule_2_2_8|bool
  tags:
      - level1
      - patch
      - rule_2.2.8

- name: "| 2.2.9 | Ensure FTP Server is not installed"
  yum:
      name: vsftpd
      state: absent
  when:
      - not rhel7cis_vsftpd_server
      - rhel7cis_rule_2_2_9|bool
  tags:
      - level1
      - patch
      - rule_2.2.9

- name: "| 2.2.10 | Ensure HTTP server is not installed"
  yum:
      name: httpd
      state: absent
  when:
      - not rhel7cis_httpd_server
      - rhel7cis_rule_2_2_10|bool
  tags:
      - level1
      - patch
      - rule_2.2.10

- name: "| 2.2.11 | Ensure IMAP and POP3 server is not installed"
  yum:
      name: dovecot
      state: absent
  when:
      - not rhel7cis_dovecot_server
      - rhel7cis_rule_2_2_11|bool
  tags:
      - level1
      - patch
      - rule_2.2.11

- name: "| 2.2.12 | Ensure Samba is not installed"
  yum:
      name: smb
      state: absent
  when:
      - not rhel7cis_smb_server
      - rhel7cis_rule_2_2_12|bool
  tags:
      - level1
      - patch
      - rule_2.2.12

- name: "| 2.2.13 | Ensure HTTP Proxy Server is not installed"
  yum:
      name: squid
      state: absent
  when:
      - not rhel7cis_squid_server
      - rhel7cis_rule_2_2_13|bool
  tags:
      - level1
      - patch
      - rule_2.2.13

- name: "| 2.2.15 | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  when:
      - not rhel7cis_is_mail_server
      - rhel7cis_rule_2_2_15|bool
  tags:
      - level1
      - patch
      - rule_2.2.15

- name: "| 2.2.16 | Ensure NIS Server is not installed"
  yum:
      name: ypserv
      state: absent
  when:
      - not rhel7cis_nis_server
      - rhel7cis_rule_2_2_16|bool
  tags:
      - level1
      - patch
      - rule_2.2.16


- name: "| 2.2.18 | Ensure telnet server is not installed"
  yum:
      name: telnet
      state: absent
  when:
      - not rhel7cis_telnet_server
      - rhel7cis_rule_2_2_18|bool
  tags:
      - level1
      - patch
      - rule_2.2.18


- name: "| 2.2.20 | Ensure rsync service is not installed"
  yum:
      name: rsyncd
      state: absent
  when:
      - not rhel7cis_rsyncd_server
      - rhel7cis_rule_2_2_20|bool
  tags:
      - level1
      - patch
      - rule_2.2.20


- name: "| 2.3.1 | Ensure NIS Client is not installed"
  yum:
      name: ypbind
      state: absent
  when:
      - not rhel7cis_ypbind_required
      - rhel7cis_rule_2_3_1|bool
  tags:
      - level1
      - patch
      - rule_2.3.1

- name: "| 2.3.2 | Ensure rsh client is not installed"
  yum:
      name: rsh
      state: absent
  when:
      - not rhel7cis_rsh_required
      - rhel7cis_rule_2_3_2|bool
  tags:
      - level1
      - patch
      - rule_2.3.2

- name: "| 2.3.3 | Ensure talk client is not installed"
  yum:
      name: talk
      state: absent
  when:
      - not rhel7cis_talk_required
      - rhel7cis_rule_2_3_3|bool
  tags:
      - level1
      - patch
      - rule_2.3.3

- name: "| 2.3.4 | Ensure telnet client is not installed"
  yum:
      name: telnet
      state: absent
  when:
      - not rhel7cis_telnet_required
      - rhel7cis_rule_2_3_4|bool
  tags:
      - level1
      - patch
      - rule_2.3.4


- name: "2.4 Ensure nonessential services are removed or masked"
  #### Notimplemented predem nelze rict, které servisy jsou nonessential
  debug:
    msg: "-->  Notimplemented predem nelze rict, které servisy jsou nonessential"
  when:
      - rhel7cis_rule_2_4|bool
  tags:
      - level1
      - rule_2.4