- name: "SCORED | 3.1.1 | PATCH | Ensure IP forwarding is disabled"
  command: "sysctl -w net.ipv4.ip_forward=0"
  when:
      - not rhel7cis_is_router
      - rhel7cis_rule_3_1_1|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.1.1

- name: "SCORED | 3.1.2 | PATCH | Ensure packet redirect sending is disabled"
  with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  command: "sysctl -w net.ipv4.ip_forward=0"
  when:
      - not rhel7cis_is_router
      - rhel7cis_rule_3_1_2|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.1.2

- name: "SCORED | 3.2.1 | PATCH | Ensure source routed packets are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }    
  when:
      - rhel7cis_rule_3_2_1|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.1

- name: "SCORED | 3.2.2 | PATCH | Ensure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes  
  with_items:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
      - { name: net.ipv4.route.flush, value: 1 }
  when:
      - rhel7cis_rule_3_2_2|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.2

- name: "SCORED | 3.2.3 | PATCH | Ensure secure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }    
  when:
      - rhel7cis_rule_3_2_3|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.3

- name: "SCORED | 3.2.4 | PATCH | Ensure suspicious packets are logged"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
  when:
      - rhel7cis_rule_3_2_4|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.4

- name: "SCORED | 3.2.5 | PATCH | Ensure broadcast ICMP requests are ignored"
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'
      state: present
      reload: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_3_2_5|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.5

- name: "SCORED | 3.2.6 | PATCH | Ensure bogus ICMP responses are ignored"
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'
      state: present
      reload: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_3_2_6|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.6

- name: "SCORED | 3.2.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.rp_filter, value: 1 }
      - { name: net.ipv4.conf.default.rp_filter, value: 1 }
      - { name: net.ipv4.route.flush, value: 1 }
  when:
      - rhel7cis_rule_3_2_7|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.7

- name: "SCORED | 3.2.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes

  when:
      - rhel7cis_rule_3_2_8|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.8

- name: "SCORED | 3.3.1 | PATCH | Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  when:
      - rhel7cis_ipv6_required | bool
      - rhel7cis_rule_3_3_1|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.1

- name: "SCORED | 3.3.2 | PATCH | Ensure IPv6 redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  when:
      - rhel7cis_ipv6_required | bool
      - rhel7cis_rule_3_3_2|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.2

- name: "NOTSCORED | 3.3.3 | PATCH | Ensure IPv6 is disabled"
  lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
      backrefs: yes
  when:
      - not rhel7cis_ipv6_required
      - rhel7cis_rule_3_3_3|bool
  tags:
      - level1
      - patch
      - rule_3.3.3

- name: "SCORED | 3.4.1 | PATCH | Ensure TCP Wrappers is installed"
  yum:
      name: tcp_wrappers
      state: present
  when:
      - rhel7cis_rule_3_4_1|bool
  tags:
      - level1
      - patch
      - rule_3.4.1

- name: "SCORED | 3.4.2 | PATCH | Ensure /etc/hosts.allow is configured"
  template:
      src: hosts.allow.j2
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_3_4_2|bool
  tags:
      - level1
      - patch
      - rule_3.4.2

- name: "SCORED | 3.4.3 | PATCH | Ensure /etc/hosts.deny is configured"
  lineinfile:
      dest: /etc/hosts.deny
      regexp: "^(#)?ALL"
      line: "ALL: ALL"
  when:
      - rhel7cis_rule_3_4_3|bool
  tags:
      - level1
      - patch
      - rule_3.4.3

- name: "SCORED | 3.4.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  file:
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_3_4_4|bool
  tags:
      - level1
      - patch
      - rule_3.4.4

- name: "SCORED | 3.4.5 | PATCH | Ensure permissions on /etc/hosts.deny are 644"
  file:
      dest: /etc/hosts.deny
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_3_4_5|bool
  tags:
      - level1
      - patch
      - rule_3.4.5



- name: "SCORED | 3.5.1.1 | PATCH | Ensure firewalld is installed and started"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.5.1.1

- name: "SCORED | 3.5.1.2 | PATCH | Ensure iptables-services package is not installed"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.5.1.2    

- name: "SCORED | 3.6.1 | PATCH | Ensure iptables is installed"
  #### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.1

- name: "SCORED | 3.6.1 | PATCH | Ensure iptables is installed and started"
  #### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.1

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.2
      - notimplemented

- name: "SCORED | 3.6.3 | PATCH | Ensure loopback traffic is configured"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.3
      - notimplemented

- name: "NOTSCORED | 3.6.4 | PATCH | Ensure outbound and established connections are configured"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.4
      - notimplemented

- name: "SCORED | 3.6.5 | PATCH | Ensure firewall rules exist for all open ports"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  tags:
      - level1
      - patch
      - rule_3.6.5

- name: "NOTSCORED | 3.7 | PATCH | Ensure wireless interfaces are disabled"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  VM servery nebudou mit wireless interface"
  tags:
      - level1
      - level2
      - patch
      - rule_3.7