- name: " 3.1.1 | Ensure IP forwarding is disabled"
  command: "sysctl -w net.ipv4.ip_forward=0"
  when:
      - not rhel7cis_is_router
      - rhel7cis_rule_3_1_1|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.1.1

- name: " 3.1.2 | Ensure packet redirect sending is disabled"
  with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  command: "sysctl -w net.ipv4.ip_forward=0"
  when:
      - not rhel7cis_is_router
      - rhel7cis_rule_3_1_2|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.1.2

- name: " 3.2.1 | Ensure source routed packets are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }    
  when:
      - rhel7cis_rule_3_2_1|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.1

- name: " 3.2.2 | Ensure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes  
  with_items:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
      - { name: net.ipv4.route.flush, value: 1 }
  when:
      - rhel7cis_rule_3_2_2|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.2

- name: " 3.2.3 | Ensure secure ICMP redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }    
  when:
      - rhel7cis_rule_3_2_3|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.3

- name: " 3.2.4 | Ensure suspicious packets are logged"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
  when:
      - rhel7cis_rule_3_2_4|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.4

- name: " 3.2.5 | Ensure broadcast ICMP requests are ignored"
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'
      state: present
      reload: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_3_2_5|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.5

- name: " 3.2.6 | Ensure bogus ICMP responses are ignored"
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'
      state: present
      reload: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_3_2_6|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.6

- name: " 3.2.7 | Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.rp_filter, value: 1 }
      - { name: net.ipv4.conf.default.rp_filter, value: 1 }
      - { name: net.ipv4.route.flush, value: 1 }
  when:
      - rhel7cis_rule_3_2_7|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.7

- name: " 3.2.8 | Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes

  when:
      - rhel7cis_rule_3_2_8|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.2.8

- name: " 3.3.1 | Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  when:
      - rhel7cis_ipv6_required | bool
      - rhel7cis_rule_3_3_1|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.1

- name: " 3.3.2 | Ensure IPv6 redirects are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  when:
      - rhel7cis_ipv6_required | bool
      - rhel7cis_rule_3_3_2|bool
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.2

- name: " 3.3.3 | Ensure IPv6 is disabled"
  lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
      backrefs: yes
  when:
      - not rhel7cis_ipv6_required
      - rhel7cis_rule_3_3_3|bool
  tags:
      - level1
      - patch
      - rule_3.3.3

- name: " 3.4.1 | Ensure TCP Wrappers is installed"
  yum:
      name: tcp_wrappers
      state: present
  when:
      - rhel7cis_rule_3_4_1|bool
  tags:
      - level1
      - patch
      - rule_3.4.1



- name: " 3.5.1.1 | Ensure firewalld is installed and started"
#### NOTIMPLEMENTED
  debug:
    msg:
     "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_5_1_1|bool   
  tags:
      - level1
      - patch
      - rule_3.5.1.1

- name: " 3.5.1.2 | Ensure iptables-services package is not installed"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_5_1_2|bool
  tags:
      - level1
      - patch
      - rule_3.5.1.2    

- name: " 3.6.1 | Ensure iptables is installed"
  #### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_1|bool 
  tags:
      - level1
      - patch
      - rule_3.6.1

- name: " 3.6.1 | Ensure iptables is installed and started"
  #### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_1|bool
  tags:
      - level1
      - patch
      - rule_3.6.1

- name: " 3.6.2 | Ensure default deny firewall policy"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_2|bool    
  tags:
      - level1
      - patch
      - rule_3.6.2

- name: " 3.6.2 | Ensure default deny firewall policy"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_2|bool
  tags:
      - level1
      - patch
      - rule_3.6.2

- name: " 3.6.2 | Ensure default deny firewall policy"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_2|bool
  tags:
      - level1
      - patch
      - rule_3.6.2
      - notimplemented

- name: " 3.6.3 | Ensure loopback traffic is configured"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_3|bool
  tags:
      - level1
      - patch
      - rule_3.6.3
      - notimplemented

- name: " 3.6.4 | Ensure outbound and established connections are configured"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_4|bool
  tags:
      - level1
      - patch
      - rule_3.6.4
      - notimplemented

- name: " 3.6.5 | Ensure firewall rules exist for all open ports"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  Notimplemented na azure vm nebudeme pouzivat lokalni FW, rizeni provozu bude reseno pomoci NSG"
  when:
      - rhel7cis_rule_3_6_5|bool
  tags:
      - level1
      - patch
      - rule_3.6.5

- name: " 3.7 | Ensure wireless interfaces are disabled"
#### NOTIMPLEMENTED
  debug:
    msg: "-->  VM servery nebudou mit wireless interface"
  when:
      - rhel7cis_rule_3_7|bool
  tags:
      - level1
      - level2
      - patch
      - rule_3.7