- name: "1.1.1.1 || Ensure mounting of cramfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install cramfs(\\s|$)"
      line: "install cramfs /bin/true"
      create: yes
  when:
      - rhel7cis_rule_1_1_1_1|bool
  tags:
      - level1
      - rule_1.1.1.1
      - cramfs
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled | modprobe
  modprobe:
    name: cramfs
    state: absent
  when:
      - rhel7cis_rule_1_1_1_1|bool
  tags:
      - level1
      - rule_1.1.1.1
      - cramfs



- name: "1.1.1.7 || Ensure mounting of udf filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install udf(\\s|$)"
      line: "install udf /bin/true"
      create: yes
  when:
      - rhel7cis_rule_1_1_1_7|bool
  tags:
      - level1
      - rule_1.1.1.7
      - udf


- name: "1.1.2 | Ensure /tmp is configured"
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: started
  when:
      - rhel7cis_rule_1_1_2|bool
  tags:
      - level2
      - rule_1.1.2

- name: "1.1.3 || Ensure nodev option set on /tmp partition\n
         1.1.4 || Ensure nosuid option set on /tmp partition\n
         1.1.5 || Ensure noexec option set on /tmp partition\n
         | drop custom tmp.mount"
  block:
    - name: 1.1.3/4/5 Ensure /tmp is configured
      copy:
        src: /usr/share/systemd/tmp.mount
        dest: /etc/systemd/system/tmp.mount
        owner: root
        group: root
        mode: 0644
        force: true
        remote_src: true
    - name: 1.1.3/4/5 Ensure /tmp is configured | edit file
      lineinfile:
        dest: /etc/systemd/system/tmp.mount
        regexp: "^Options=mode="
        line: "Options=mode=1777,strictatime,nosuid,nodev,noexec,size={{ temp_dir_size }}"
    - name: 1.1.3/4/5 Ensure /tmp is configured | reload demon
      systemd:
        daemon_reload: yes
    - name: 1.1.3/4/5 Ensure /tmp is configured | enable and start tmp.mount
      systemd:
        name: tmp.mount
        enabled: yes
        masked: no
        state: started
  when:
      - tmp_mount.stat.exists
      - rhel7cis_rule_1_1_3|bool
      - rhel7cis_rule_1_1_4|bool
      - rhel7cis_rule_1_1_5|bool
  tags:
      - level1
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5

- name: "1.1.8  || Ensure nodev option set on /var/tmp partition\n
         1.1.9  || Ensure nosuid option set on /var/tmp partition\n
         1.1.10 || Ensure noexec option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ rhel7cis_vartmp['source'] }}"
      state: present
      fstype: "{{ rhel7cis_vartmp['fstype'] }}"
      opts: "{{ rhel7cis_vartmp['opts'] }}"
  when:
      - rhel7cis_vartmp['enabled']
      - rhel7cis_rule_1_1_8|bool
      - rhel7cis_rule_1_1_9|bool
      - rhel7cis_rule_1_1_10|bool
  tags:
      - level1
      - rule_1.1.8
      - rule_1.1.9
      - rule_1.1.10

- name: "1.1.14 || Ensure nodev option set on /home partition"
  command: "mount -o remount,nodev /home"
  when:
      - rhel7cis_rule_1_1_14|bool
      - tmp_mount.stat.exists
  tags:
      - level1
      - rule_1.1.14

- name: "1.1.6 || Ensure /dev/shm is configured\n
         1.1.15 || Ensure nodev option set on /dev/shm partition\n
         1.1.16 || Ensure nosuid option set on /dev/shm partition\n
         1.1.17 || Ensure noexec option set on /dev/shm partition"
  mount:
      name: /dev/shm
      src: tmpfs
      state: mounted
      fstype: tmpfs
      opts: "defaults,nodev,nosuid,noexec"
  when:
      - rhel7cis_rule_1_1_15|bool
      - rhel7cis_rule_1_1_16|bool
      - rhel7cis_rule_1_1_17|bool
  tags:
      - level1
      - rule_1.1.15
      - rule_1.1.16
      - rule_1.1.17

- name: "1.1.18 || Ensure nodev option set on removable media partitions"
  #### Notimplemented manual step
  debug:
    msg: "--> Notimplemented manual step"
  changed_when: no
  when:
      - rhel7cis_rule_1_1_18|bool
  tags:
      - level1
      - rule_1.1.18

- name: "1.1.19 || Ensure nosuid option set on removable media partitions"
  #### Notimplemented manual step
  debug:
    msg: "--> Notimplemented manual step"
  changed_when: no
  when:
      - rhel7cis_rule_1_1_19|bool
  tags:
      - level1
      - rule_1.1.19

- name: "1.1.20 || Ensure noexec option set on removable media partitions"
    #### Notimplemented manual step
  debug:
    msg: "--> Notimplemented manual step"
  changed_when: no
  when:
      - rhel7cis_rule_1_1_20|bool
  tags:
      - level1
      - rule_1.1.20

- name: "1.1.21 || Ensure sticky bit is set on all world-writable directories"
  shell: set -o pipefail && df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: no
  failed_when: no
  when:
      - rhel7cis_rule_1_1_21|bool
  tags:
      - level1
      - rule_1.1.21

- name: "1.1.22 || Disable Automounting"
  service:
      name: autofs
      enabled: no
  when:
      - not rhel7cis_allow_autofs
      - autofs_service_status.stdout == "loaded"
      - rhel7cis_rule_1_1_22|bool
  tags:
      - level1
      - rule_1.1.22

- name: "Disable USB Storage | 1.2.24"
  #### Notimplemented Migrace je na urovni pouziti pouze virtualnich VM, ke kterym nelze USB pripojit (na urovni Azure VM)
  debug:
    msg: "-->  Notimplemented Migrace je na urovni pouziti pouze virtualnich VM, ke kterym nelze USB pripojit (na urovni Azure VM)"
  when:
      - rhel7cis_rule_1_1_24|bool
  tags:
      - level1
      - rule_1.1.24


- name: "1.2.1 || Ensure package manager repositories are configured"
  command: yum check-update
  args:
      warn: false
  register: yum_configured
  changed_when: no
  failed_when: no
  when:
      - rhel7cis_rule_1_2_1|bool
  tags:
      - level1
      - rule_1.2.1

- name: "1.2.2 || Ensure gpgcheck is globally activated"
  replace:
      name: /etc/yum.conf
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
  when:
      - rhel7cis_rule_1_2_2|bool
  tags:
      - level1
      - rule_1.2.2

- name: "1.2.2 || Ensure gpgcheck is globally activated"
  find:
      paths: /etc/yum.repos.d
      patterns: "*.repo"
  register: yum_repos
  changed_when: no
  when:
      - rhel7cis_rule_1_2_2|bool
  tags:
      - level1
      - rule_1.2.2

- name: "1.2.2 || Ensure gpgcheck is globally activated"
  replace:
      name: "{{ item.path }}"
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
  with_items:
      - "{{ yum_repos.files }}"
  when:
      - rhel7cis_rule_1_2_2|bool
  tags:
      - level1
      - rule_1.2.2

- name: "1.2.3 | AUDIT | Ensure GPG keys are configured"
  command: rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
  changed_when: no
  when:
      - rhel7cis_rule_1_2_3|bool 
  tags:
      - level1
      - rule_1.2.3

- name: "1.2.6 | Ensure sudo is installed"
  yum:
    name: sudo
    state: present
  when:
      - rhel7cis_rule_1_2_6|bool
  tags:
      - level1
      - rule_1.2.6

- name: "1.2.7 | Ensure sudo commands use pty"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^Defaults use_pty"
    line: "Defaults use_pty"
    validate: "visudo -cf %s"
  when:
      - rhel7cis_rule_1_2_7|bool
  tags:
      - level1
      - rule_1.2.7

- name: "1.2.8 | Ensure sudo log file exists"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^Defaults logfile.*"
    line: 'Defaults logfile="/var/log/sudo.log"'
    validate: "visudo -cf %s"
  when:
      - rhel7cis_rule_1_2_8|bool
  tags:
      - level1
      - rule_1.2.8

- name: "1.3.1 || Ensure AIDE is installed"
  yum:
      name: aide
      state: present
  when:
      - rhel7cis_rule_1_3_1|bool
  tags:
      - level1
      - aide
      - rule_1.3.1

- name: "1.3.1 || Ensure AIDE is installed"
  command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  args:
      creates: /var/lib/aide/aide.db.gz
  changed_when: no
  failed_when: no
  async: 45
  poll: 0
  when:
      - rhel7cis_config_aide|bool
      - rhel7cis_rule_1_3_1|bool
      - not ansible_check_mode
  tags:
      - level1
      - aide
      - rule_1.3.1

- name: "1.3.2 || Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check
      cron_file: "{{ rhel7cis_aide_cron['cron_file'] }}"
      user: "{{ rhel7cis_aide_cron['cron_user'] }}"
      minute: "{{ rhel7cis_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ rhel7cis_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ rhel7cis_aide_cron['aide_day'] | default('*') }}"
      month: "{{ rhel7cis_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ rhel7cis_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ rhel7cis_aide_cron['aide_job'] }}"
  when:
      - rhel7cis_rule_1_3_2|bool
  tags:
      - level1
      - aide
      - rule_1.3.2

- name: "1.4.1 || Ensure permissions on bootloader config are configured"
  stat:
      path: /etc/grub2.cfg
  register: grub_cfg
  when:
      - rhel7cis_rule_1_4_1|bool
  tags:
      - level1
      - grub
      - rule_1.4.1

- name: "1.4.1 || Ensure permissions on bootloader config are configured"
  file:
      path: "{{ grub_cfg.stat.lnk_source }}"
      owner: root
      group: root
      mode: 0600
  when:
      - rhel7cis_rule_1_4_1|bool
      - grub_cfg.stat.exists and grub_cfg.stat.islnk
  tags:
      - level1
      - grub
      - rule_1.4.1

- name: 1.4.2 Ensure bootloader password is set
#### NOTIMPLEMENTED
  debug:
    msg:
     "-->  Notimplemented Heslo na bootloaderu neresime, protože secure boot je zajisteni na urovni virtual serveru (RBAC + enkrypce disku)"
  when:
      - rhel7cis_rule_1_4_2|bool
  tags:
    - level1
    - rule_1.4.2



- name: "1.4.3 || Ensure authentication required for single user mode"
  block:
      - name: "1.4.3 || Ensure authentication required for single user mode - Emergency"
        lineinfile:
            dest: /usr/lib/systemd/system/emergency.service
            regexp: '/sbin/sulogin'
            line: 'ExecStart=-/bin/sh -c \"/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default\"'
        when:
            - rhel7cis_rule_1_4_3|bool
           # - ansible_distribution_major_version == 7
        tags:
            - level1
            - level2
      
            - rule_1.4.3
      - name: "1.4.3 || Ensure authentication required for single user mode - Rescue"
        lineinfile:
            dest: /usr/lib/systemd/system/rescue.service
            regexp: '/sbin/sulogin'
            line: 'ExecStart=-/bin/sh -c \"/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default\"'
        when:
            - rhel7cis_rule_1_4_3|bool
           # - ansible_distribution_major_version == 7
        tags:
            - level1
            - level2
      
            - rule_1.4.3

- name: "1.5.1 || Ensure core dumps are restricted"
  lineinfile:
      state: present
      dest: /etc/security/limits.conf
      regexp: '^#?\\*.*core'
      line: '*                hard    core            0'
      insertbefore: '^# End of file'
  when:
      - rhel7cis_rule_1_5_1|bool
  tags:
      - level1
      - rule_1.5.1

- name: "1.5.1 || Ensure core dumps are restricted"
  sysctl:
      name: fs.suid_dumpable
      value: '0'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_1_5_1|bool
  tags:
      - level1
      - rule_1.5.1

- name: "1.5.2 || Ensure XD/NX support is enabled"
  shell: set -o pipefail && dmesg | grep -E "NX|XD" | grep " active"
  changed_when: no
  when:
      - rhel7cis_rule_1_5_2|bool
  tags:
      - level1
      - rule_1.5.2

- name: "1.5.3 || Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: kernel.randomize_va_space
      value: '2'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_1_5_3|bool
  tags:
      - level1
      - rule_1.5.3

- name: "1.5.4 || Ensure prelink is disabled"
  command: prelink -ua
  when:
      - prelink_installed.rc == 0
      - rhel7cis_rule_1_5_4|bool
  tags:
      - level1
      - rule_1.5.4

- name: "1.5.4 || Ensure prelink is disabled"
  yum:
      name: prelink
      state: absent
  when:
      - rhel7cis_rule_1_5_4|bool
  tags:
      - level1
      - rule_1.5.4

- name: "1.6.2 || Ensure SELinux is installed"
  yum:
      name: libselinux
      state: present
  when:
      - rhel7cis_rule_1_6_2|bool
  tags:
      - level2
      - rule_1.6.2

- name: "1.6.1.1 || Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
      follow: yes
  register: selinux_grub_patch
  ignore_errors: yes
  notify: generate new grub config
  when:
      - rhel7cis_rule_1_6_1_1|bool
  tags:
      - level2
      - rule_1.6.1.1

- name: "1.6.1.2 || Ensure the SELinux mode is enforcing or permissive | enforcing"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ rhel7cis_selinux_pol }}"
      state: enforcing
  when:
      - not rhel7cis_selinux_disable|bool
      - rhel7cis_rule_1_6_1_2|bool
  tags:
      - level1
      - selinux
      - rule_1.6.1.2

- name: "1.6.1.3 || Ensure SELinux policy is configured"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ rhel7cis_selinux_pol }}"
      state: enforcing
  when:
      - not rhel7cis_selinux_disable|bool
      - rhel7cis_rule_1_6_1_3|bool
  tags:
      - level2
      - selinux
      - rule_1.6.1.3

- name: "1.6.1.4 || Ensure SETroubleshoot is not installed"
  yum:
      name: setroubleshoot
      state: absent
  when:
      - rhel7cis_rule_1_6_1_4|bool
  tags:
      - level1
      - selinux
      - rule_1.6.1.4

- name: "1.6.1.5 || Ensure the MCS Translation Service (mcstrans) is not installed"
  yum:
      name: mcstrans
      state: absent
  when:
      - rhel7cis_rule_1_6_1_5|bool
  tags:
      - level2
      - rule_1.6.1.5



- name: "1.7.1.1 || Ensure message of the day is configured properly"
  template:
      src: etc/motd.j2
      dest: /etc/motd
  when:
      - rhel7cis_rule_1_7_1_1|bool
  tags:
      - level1
      - banner
      - rule_1.7.1.1

- name: "NOT1.7.1.2 || Ensure local login warning banner is configured properly"
  template:
      src: etc/issue.j2
      dest: /etc/issue
  when:
      - rhel7cis_rule_1_7_1_2|bool
  tags:
      - level1
      - rule_1.7.1.2

- name: "NOT1.7.1.3 || Ensure remote login warning banner is configured properly"
  template:
      src: etc/issue.net.j2
      dest: /etc/issue.net
  when:
      - rhel7cis_rule_1_7_1_3|bool
  tags:
      - level1
      - banner
      - rule_1.7.1.3

- name: "NOT1.7.1.4 || Ensure permissions on /etc/motd are configured"
  file:
      dest: /etc/motd
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_1_7_1_4|bool
  tags:
      - level1
      - perms
      - rule_1.7.1.4

- name: "1.7.1.5 || Ensure permissions on /etc/issue are configured"
  file:
      dest: /etc/issue
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_1_7_1_5|bool
  tags:
      - level1
      - perms
      - rule_1.7.1.5

- name: "NOT1.7.1.6 || Ensure permissions on /etc/issue.net are configured"
  file:
      dest: /etc/issue.net
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_rule_1_7_1_6|bool
  tags:
      - level1
      - perms
      - rule_1.7.1.6

- name: "1.7.2 || Ensure GDM is removed or login is configured"
  yum:
      name: gmd
      state: absent
  when:
      - rhel7cis_rule_1_7_2|bool
  tags:
      - level1
      - rule_1.7.2

- name: "1.8 || Ensure updates, patches, and additional security software are installed"
  yum:
      name: "*"
      state: latest
  when:
      - rhel7cis_rule_1_8|bool
  tags:
      - level1
      - rule_1.8
